EXPORT_TYPE_ENUM_MODEL = 'MODEL'
EXPORT_TYPE_ENUM_ANIMATION = 'ANIMATION'
EXPORT_TYPE_ENUM_RIG = 'RIG'

EXPORT_TYPE_ENUM_ITEMS = [
    (EXPORT_TYPE_ENUM_MODEL, EXPORT_TYPE_ENUM_MODEL.title(), ''),
    (EXPORT_TYPE_ENUM_ANIMATION, EXPORT_TYPE_ENUM_ANIMATION.title(), ''),
    (EXPORT_TYPE_ENUM_RIG, EXPORT_TYPE_ENUM_RIG.title(), '')
]

ASSET_TYPE_ENUM_ITEMS = [
    ('CHARACTER', 'Character', ''),
    ('ACTOR', 'Actor', 'Rigged props'),
    ('PROP', 'Prop', '')
]